CREATE TABLE IF NOT EXISTS Groups(
       ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
       Name VARCHAR(50) NOT NULL UNIQUE,
       Owner INT NOT NULL,
       FOREIGN KEY(Owner) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Sessions(
       ID INT NOT NULL PRIMARY KEY,
       GroupID INTEGER,
       Time DATETIME NOT NULL,
       FOREIGN KEY(GroupID) REFERENCES Groups(ID)
);       

       
