#!/usr/bin/env bash

#This should get changed before we submit this
DB=testDB.db

#Sets the cli options
OPTSTRING=":ugrsiRa"
declare -a options=()

#This runs if you don't pass any arguments. It's the same as passing '-a'
if [ -z ${1} ]
then
    options+=("users" "groups" "rpgs" "ratings" "sessions" "intermediaries")
fi

while getopts ${OPTSTRING} opt; do
    case ${opt} in
        u)
            options+=("users")
            ;;
        g)
            options+=("groups")
            ;;
        r)
            options+=("ratings")
            ;;
        R)
            options+=("rpgs")
            ;;
        s)
            options+=("sessions")
            ;;
     
        i)
            options+=("intermediaries")
            ;;
        a)
            options+=("users" "groups" "rpgs" "ratings" "sessions" "intermediaries")
            ;;
        ?)        
        echo "Invalid option '-${OPTARG}'"
        echo "Valid options are:"
        echo "-u = users"
        echo "-g = groups"
        echo "-r = ratings"
        echo "-s = sessions"
        echo "-i = intermediary tables"
        echo "-R = Rpg table"

        exit 1
        ;;      
    esac
done

init_users ()
{
    echo "Initializing Users table"
    cat users.sql | sqlite3 $DB
}

init_groups ()
{
    echo "Initializing Groups table"
    cat groups.sql | sqlite3 $DB
}
init_ratings()
{
    echo "Initializing Ratings table"
    cat ratings.sql | sqlite3 $DB
}
init_sessions()
{
    echo "Initializing Sessions table"
    cat sessions.sql | sqlite3 $DB
}
init_rpg()
{
    echo "Initializing the RPG table"
    cat rpg.sql | sqlite3 $DB
}
init_intermediary()
{
    echo "Initializing the Intermediary tables"
    cat intermediary.sql | sqlite3 $DB
}

create_initial_data()
{
    if [ "${1}" == "users" ]
    then
        init_users
    elif [ "${1}" == "groups" ]
    then
        init_groups
    elif [ "${1}" == "ratings" ]
    then
        init_ratings
    elif [ "${1}" == "sessions" ]
    then
        init_sessions
    elif [ "${1}" == "rpgs" ]
    then
        init_rpg
    elif [ "${1}" == "intermediaries" ]
    then
        init_intermediary
    else
        echo "This should not be possible (invalid input)"
    fi
}
for i in "${options[@]}"
do
    echo $i
    create_initial_data $i
done
